# AAI614: Data Science & its Applications

### *Week 3: Practical Exercise with Data Cleaning*
**Assignment:** Use the dataset from the Mercari Price Suggestion Challenge, and use OpenRefine to clean the data.

In [1]:
import pandas as pd
import numpy as np

In [7]:
#offline mode
train_before_clearning = pd.read_csv("before.tsv", sep="\t")
train_after_cleaning   = pd.read_csv("after.tsv",  sep="\t")

print("Before cleaning:", train_before_clearning.shape)
print("After cleaning: ", train_after_cleaning.shape)

Before cleaning: (1482535, 8)
After cleaning:  (1476208, 13)

**1. DataStet Before Data Cleaning**

In [8]:
train_before_clearning.head()

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description
0,0,MLB Cincinnati Reds T Shirt Size XL,3,Men/Tops/T-shirts,NaN,10.0,1,No description yet
1,1,Razer BlackWidow Chroma Keyboard,3,Electronics/Computers & Tablets/Components & P...,Razer,52.0,0,This keyboard is in great condition and works ...
2,2,AVA-VIV Blouse,1,Women/Tops & Blouses/Blouse,Target,10.0,1,Adorable top with a hint of lace and a key hol...
3,3,Leather Horse Statues,1,Home/Home Décor/Home Décor Accents,NaN,35.0,1,New with tags. Leather horses. Retail for [rm]...
4,4,24K GOLD plated rose,1,Women/Jewelry/Necklaces,NaN,44.0,0,Complete with certificate of authenticity

**2. DataStet After Data Cleaning**

In [9]:
train_after_cleaning.head()

,train_id,name,item_condition_id,category_name,category_name 1,category_name 2,category_name 3,brand_name,price,high_priced,shipping,item_description,has_offer
0,0,MLB Cincinnati Reds T Shirt Size XL,3,Men/Tops/T-shirts,Men,Tops,T-shirts,Unbranded,10.0,0,1,No description yet,0.0
1,1,Razer BlackWidow Chroma Keyboard,3,Electronics/Computers & Tablets/Components & P...,Electronics,Computers & Tablets,Components & Parts,Razer,52.0,0,0,This keyboard is in great condition and works ...,0.0
2,2,AVA-VIV Blouse,1,Women/Tops & Blouses/Blouse,Women,Tops & Blouses,Blouse,Target,10.0,0,1,Adorable top with a hint of lace and a key hol...,0.0
3,3,Leather Horse Statues,1,Home/Home Décor/Home Décor Accents,Home,Home Décor,Home Décor Accents,Unbranded,35.0,0,1,New with tags. Leather horses. Retail for [rm]...,0.0
4,4,24K GOLD plated rose,1,Women/Jewelry/Necklaces,Women,Jewelry,Necklaces,Unbranded,44.0,0,0,Complete with certificate of authenticity,0.0