# AAI614: Data Science & its Applications

*Notebook 3.1: Practice with Data Collections*

<a href="https://colab.research.google.com/github/engmahmoudelhassan-cell/AAI614_Elhassan/blob/main/Week%203/Notebook3.1-M.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source: Scraping with Python http://shop.oreilly.com/product/0636920034391.do

In [1]:
# Run this cell first. One helper that all the cells below use.
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AAI614 practice'}

def get_soup(url):
    """Open a URL with a real User-Agent (avoids Wikipedia's 403) and return BeautifulSoup."""
    req = Request(url, headers=HEADERS)
    return BeautifulSoup(urlopen(req, timeout=15), 'html.parser')

## List every link on a page

In [2]:
bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')

for link in bs.find_all('a'):
    if 'href' in link.attrs:
        print(link.attrs['href'])

#bodyContent
/wiki/Main_Page
/wiki/Wikipedia:Contents
/wiki/Portal:Current_events
/wiki/Special:Random
/wiki/Wikipedia:About
//en.wikipedia.org/wiki/Wikipedia:Contact_us
/wiki/Help:Contents
/wiki/Help:Introduction
/wiki/Wikipedia:Community_portal
/wiki/Special:RecentChanges
/wiki/Wikipedia:File_upload_wizard
/wiki/Special:SpecialPages
/w/index.php?title=Special:DownloadAsPdf&page=Kevin_Bacon&action=show-download-screen
/w/index.php?title=Kevin_Bacon&printable=yes
https://commons.wikimedia.org/wiki/Kevin_Bacon
https://www.wikidata.org/wiki/Special:EntityPage/Q3454165
/wiki/Main_Page
/wiki/Special:Search
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en
/w/index.php?title=Special:CreateAccount&returnto=Kevin+Bacon
/w/index.php?title=Special:UserLogin&returnto=Kevin+Bacon
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en
/w/index.php?title=Special:CreateAccount&returnto=Kevin+Bacon
/w/index.php?title=Special:UserLogin&returnto=Kevin+Bacon
#
#Early_life_and_education
#Acting_career
#Early_work
#1980s
#1990s
#2000s
#2010s
#Other_ventures
#Six_Degrees_of_Kevin_Bacon
#Personal_life
#Accolades
#Awards_and_nominations
#Other_honors
#See_also
#References
#External_links
https://af.wikipedia.org/wiki/Kevin_Bacon
https://an.wikipedia.org/wiki/Kevin_Bacon
https://ar.wikipedia.org/wiki/%D9%83%D9%8A%D9%81%D9%8A%D9%86_%D8%A8%D9%8A%D9%83%D9%86
https://arz.wikipedia.org/wiki/%D9%83%D9%8A%D9%81%D9%8A%D9%86_%D8%A8%D9%8A%D9%83%D9%86
https://ast.wikipedia.org/wiki/Kevin_Bacon
https://azb.wikipedia.org/wiki/%DA%A9%D9%88%DB%8C%D9%86_%D8%A8%DB%8C%DA%A9%D9%86
https://be.wikipedia.org/wiki/%D0%9A%D0%B5%D0%B2%D1%96%D0%BD_%D0%91%D1%8D%D0%B9%D0%BA%D0%B0%D0%BD
https://bg.wikipedia.org/wiki/%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD_%D0%91%D0%B5%D0%B9%D0%BA%D1%8A%D0%BD
https://bi.wikipedia.org/wiki/Kevin_Bacon
https://bs.wikipedia.org/wiki/Kevin_Bacon
https://ca.wikipedia.org/wiki/Kevin_Bacon
https://ckb.wikipedia.org/wiki/%DA%A9%DB%8E%DA%A4%D9%86_%D8%A8%DB%95%DB%8C%DA%A9%D9%86
https://cs.wikipedia.org/wiki/Kevin_Bacon
https://da.wikipedia.org/wiki/Kevin_Bacon
https://de.wikipedia.org/wiki/Kevin_Bacon
https://el.wikipedia.org/wiki/%CE%9A%CE%AD%CE%B2%CE%B9%CE%BD_%CE%9C%CF%80%CE%AD%CE%B9%CE%BA%CE%BF%CE%BD
https://eml.wikipedia.org/wiki/Kevin_Bacon
https://eo.wikipedia.org/wiki/Kevin_Bacon
https://es.wikipedia.org/wiki/Kevin_Bacon
https://eu.wikipedia.org/wiki/Kevin_Bacon
https://fa.wikipedia.org/wiki/%DA%A9%D9%88%DB%8C%D9%86_%D8%A8%DB%8C%DA%A9%D9%86
https://fi.wikipedia.org/wiki/Kevin_Bacon
https://fr.wikipedia.org/wiki/Kevin_Bacon
https://ga.wikipedia.org/wiki/Kevin_Bacon
https://gl.wikipedia.org/wiki/Kevin_Bacon
https://he.wikipedia.org/wiki/%D7%A7%D7%95%D7%95%D7%99%D7%9F_%D7%91%D7%99%D7%99%D7%A7%D7%95%D7%9F
https://hr.wikipedia.org/wiki/Kevin_Bacon
https://hu.wikipedia.org/wiki/Kevin_Bacon
https://hy.wikipedia.org/wiki/%D5%94%D6%87%D5%AB%D5%B6_%D4%B2%D5%A5%D5%B5%D6%84%D5%B8%D5%B6
https://id.wikipedia.org/wiki/Kevin_Bacon
https://io.wikipedia.org/wiki/Kevin_Bacon
https://it.wikipedia.org/wiki/Kevin_Bacon
https://ja.wikipedia.org/wiki/%E3%82%B1%E3%83%B4%E3%82%A3%E3%83%B3%E3%83%BB%E3%83%99%E3%83%BC%E3%82%B3%E3%83%B3
https://ka.wikipedia.org/wiki/%E1%83%99%E1%83%94%E1%83%95%E1%83%98%E1%83%9C_%E1%83%91%E1%83%94%E1%83%98%E1%83%99%E1%83%9D%E1%83%9C%E1%83%98
https://kk.wikipedia.org/wiki/%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD_%D0%91%D1%8D%D0%B9%D0%BA%D0%BE%D0%BD
https://ko.wikipedia.org/wiki/%EC%BC%80%EB%B9%88_%EB%B2%A0%EC%9D%B4%EC%BB%A8
https://lv.wikipedia.org/wiki/Kevins_Beikons
https://mn.wikipedia.org/wiki/%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD_%D0%91%D1%8D%D0%B9%D0%BA%D0%BE%D0%BD
https://ms.wikipedia.org/wiki/Kevin_Bacon
https://nl.wikipedia.org/wiki/Kevin_Bacon
https://no.wikipedia.org/wiki/Kevin_Bacon
https://oc.wikipedia.org/wiki/Kevin_Bacon
https://pl.wikipedia.org/wiki/Kevin_Bacon
https://pt.wikipedia.org/wiki/Kevin_Bacon
https://ro.wikipedia.org/wiki/Kevin_Bacon
https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D0%B9%D0%BA%D0%BE%D0%BD,_%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD
https://sco.wikipedia.org/wiki/Kevin_Bacon
https://sh.wikipedia.org/wiki/Kevin_Bacon
https://simple.wikipedia.org/wiki/Kevin_Bacon
https://sk.wikipedia.org/wiki/Kevin_Bacon
https://sr.wikipedia.org/wiki/%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD_%D0%91%D0%B5%D1%98%D0%BA%D0%BE%D0%BD
https://sv.wikipedia.org/wiki/Kevin_Bacon
https://th.wikipedia.org/wiki/%E0%B9%80%E0%B8%84%E0%B8%A7%E0%B8%B4%E0%B8%99_%E0%B9%80%E0%B8%9A%E0%B8%84%E0%B8%AD%E0%B8%99
https://tr.wikipedia.org/wiki/Kevin_Bacon
https://uk.wikipedia.org/wiki/%D0%9A%D0%B5%D0%B2%D1%96%D0%BD_%D0%91%D0%B5%D0%B9%D0%BA%D0%BE%D0%BD
https://ur.wikipedia.org/wiki/%DA%A9%DB%8C%D9%88%D9%86_%D8%A8%DB%8C%DA%A9%D9%86
https://uz.wikipedia.org/wiki/Kevin_Bacon
https://vi.wikipedia.org/wiki/Kevin_Bacon
https://wuu.wikipedia.org/wiki/%E5%87%AF%E6%96%87%C2%B7%E8%B4%9D%E8%82%AF
https://xmf.wikipedia.org/wiki/%E1%83%99%E1%83%94%E1%83%95%E1%83%98%E1%83%9C_%E1%83%91%E1%83%94%E1%83%98%E1%83%99%E1%83%9D%E1%83%9C%E1%83%98
https://zh-min-nan.wikipedia.org/wiki/Kevin_Bacon
https://zh-yue.wikipedia.org/wiki/%E5%A5%87%E9%9B%B2%E8%B2%9D%E6%A0%B9
https://zh.wikipedia.org/wiki/%E5%87%AF%E6%96%87%C2%B7%E8%B4%9D%E8%82%AF
https://www.wikidata.org/wiki/Special:EntityPage/Q3454165#sitelinks-wikipedia
/wiki/Kevin_Bacon
/wiki/Talk:Kevin_Bacon
/wiki/Kevin_Bacon
/w/index.php?title=Kevin_Bacon&action=edit
/w/index.php?title=Kevin_Bacon&action=history
/wiki/Kevin_Bacon
/w/index.php?title=Kevin_Bacon&action=edit
/w/index.php?title=Kevin_Bacon&action=history
/wiki/Special:WhatLinksHere/Kevin_Bacon
/wiki/Special:RecentChangesLinked/Kevin_Bacon
//en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard
/w/index.php?title=Kevin_Bacon&oldid=1357713230
/w/index.php?title=Kevin_Bacon&action=info
/w/index.php?title=Special:CiteThisPage&page=Kevin_Bacon&id=1357713230&wpFormIdentifier=titleform
/w/index.php?title=Special:UrlShortener&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FKevin_Bacon
/w/index.php?title=Special:DownloadAsPdf&page=Kevin_Bacon&action=show-download-screen
/w/index.php?title=Kevin_Bacon&printable=yes
https://commons.wikimedia.org/wiki/Kevin_Bacon
https://www.wikidata.org/wiki/Special:EntityPage/Q3454165
/wiki/Wikipedia:Protection_policy#semi
/wiki/Kevin_Bacon_(disambiguation)
/wiki/File:Kevin_Bacon_The_Best_You_Can-55_(cropped).jpg
/wiki/Philadelphia
/wiki/Kevin_Bacon_filmography
/wiki/Kyra_Sedgwick
/wiki/Sosie_Bacon
/wiki/Edmund_Bacon_(architect)
/wiki/Michael_Bacon_(composer)
http://baconbros.com
#cite_note-1
#cite_note-actor-2
/wiki/Leading_man
/wiki/Golden_Globe_Award
/wiki/Actor_Award
/wiki/National_Lampoon%27s_Animal_House
/wiki/Diner_(1982_film)
/wiki/Footloose_(1984_film)
/wiki/JFK_(film)
/wiki/A_Few_Good_Men
/wiki/Apollo_13_(film)
/wiki/Mystic_River_(film)
/wiki/Frost/Nixon_(film)
/wiki/Friday_the_13th_(1980_film)
/wiki/Tremors_(1990_film)
/wiki/The_River_Wild
/wiki/Balto_(film)
/wiki/The_Woodsman_(2004_film)
/wiki/Crazy,_Stupid,_Love
/wiki/X-Men:_First_Class
/wiki/Patriots_Day_(film)
/wiki/Losing_Chase
/wiki/Loverboy_(2005_film)
/wiki/Golden_Globe_Award_for_Best_Actor_%E2%80%93_Miniseries_or_Television_Film
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Miniseries_or_Television_Movie
/wiki/Michael_Strobl
/wiki/HBO
/wiki/Taking_Chance
/wiki/Fox_Broadcasting_Company
/wiki/The_Following
/wiki/Amazon_Prime_Video
/wiki/I_Love_Dick_(TV_series)
/wiki/Showtime_(TV_network)
/wiki/City_on_a_Hill_(TV_series)
#cite_note-3
/wiki/Hollywood_Walk_of_Fame
#cite_note-4
/wiki/Six_Degrees_of_Kevin_Bacon
/wiki/Brand_ambassador
/wiki/EE_(telecommunications)
#cite_note-5
/wiki/Kyra_Sedgwick
/wiki/Philadelphia
#cite_note-actor-2
/wiki/Birth_name#Maiden_and_married_names
#cite_note-actor-2
/wiki/Edmund_Bacon_(architect)
/wiki/Urban_planning
/wiki/Design_of_Cities
#cite_note-bacon-6
/wiki/Julia_R._Masterman_School
/wiki/Spring_Garden,_Philadelphia
#cite_note-7
/wiki/Pennsylvania_Governor%27s_School_for_the_Arts
/wiki/Bucknell_University
/wiki/Lewisburg,_Pennsylvania
#cite_note-8
/wiki/Glory_Van_Scott
#cite_note-walk-9
#cite_note-bacon-6
/wiki/Kevin_Bacon_filmography
/wiki/Circle_in_the_Square
/wiki/Nancy_Mills
/wiki/Cosmopolitan_(magazine)
#cite_note-cosmo91-10
/wiki/Fraternities_and_sororities
/wiki/Animal_House
#cite_note-bacon-6
/wiki/Search_for_Tomorrow
/wiki/Guiding_Light
/wiki/Friday_the_13th_(1980_film)
#cite_note-11
/wiki/Getting_Out
/wiki/Phoenix_Theater
/wiki/Flux
/wiki/Second_Stage_Theatre
#cite_note-bio-12
/wiki/Obie_Award
/wiki/Forty_Deuce
#cite_note-kevin-13
/wiki/Slab_Boys
/wiki/Sean_Penn
/wiki/Val_Kilmer
/wiki/Barry_Levinson
/wiki/Diner_(1982_film)
/wiki/Steve_Guttenberg
/wiki/Daniel_Stern_(actor)
/wiki/Mickey_Rourke
/wiki/Tim_Daly
/wiki/Ellen_Barkin
#cite_note-14
/wiki/Footloose_(1984_film)
#cite_note-bio-12
/wiki/James_Dean
/wiki/Rebel_Without_a_Cause
/wiki/Mickey_Rooney
/wiki/Judy_Garland
#cite_note-time84-15
#cite_note-bacon-6
#cite_note-16
#cite_note-17
/wiki/Typecasting_(acting)
/wiki/John_Hughes_(filmmaker)
/wiki/Planes,_Trains_and_Automobiles
#cite_note-18
/wiki/She%27s_Having_a_Baby
#cite_note-bio-12
/wiki/The_Big_Picture_(1989_film)
#cite_note-19
/wiki/Tremors_(1990_film)
#cite_note-20
/wiki/Joel_Schumacher
/wiki/Flatliners
#cite_note-bio-12
/wiki/Elizabeth_Perkins
/wiki/He_Said,_She_Said_(film)
#cite_note-bio-12
/wiki/The_New_York_Times
#cite_note-nyt94-21
/wiki/Oliver_Stone
/wiki/JFK_(film)
#cite_note-22
/wiki/A_Few_Good_Men_(film)
#cite_note-23
/wiki/Michael_Greif
#cite_note-bio-12
/wiki/Golden_Globe_Award
/wiki/The_River_Wild
#cite_note-bio-12
/wiki/Meryl_Streep
/wiki/Murder_in_the_First_(film)
#cite_note-bio-12
/wiki/Blockbuster_(entertainment)
/wiki/Apollo_13_(film)
#cite_note-24
/wiki/Sleepers_(film)
#cite_note-25
/wiki/Picture_Perfect_(1997_film)
#cite_note-bio-12
/wiki/Losing_Chase
#cite_note-austin-26
/wiki/Digging_to_China
#cite_note-bio-12
/wiki/Payola
/wiki/Telling_Lies_in_America_(film)
#cite_note-bio-12
/wiki/Wild_Things_(film)
/wiki/Stir_of_Echoes
/wiki/David_Koepp
#cite_note-27
/wiki/File:Kevin_Bacon_Cannes_2004.jpg
/wiki/Cannes_Film_Festival
/wiki/Paul_Verhoeven
/wiki/Hollow_Man
#cite_note-28
/wiki/Colin_Firth
/wiki/Rachel_Blanchard
/wiki/M%C3%A9nage_%C3%A0_trois
/wiki/Where_the_Truth_Lies
#cite_note-29
/wiki/Atom_Egoyan
/wiki/MPAA
/wiki/MPAA_film_rating_system
#cite_note-30
/wiki/Help:Archiving_a_source
/wiki/My_Dog_Skip_(film)
#cite_note-31
/wiki/Sean_Penn
/wiki/Tim_Robbins
/wiki/Clint_Eastwood
/wiki/Mystic_River_(film)
/wiki/The_Woodsman_(2004_film)
#cite_note-32
/wiki/Beauty_Shop
/wiki/Queen_Latifah
/wiki/HBO_Films
/wiki/Taking_Chance
/wiki/Michael_Strobl
/wiki/Desert_Storm
#cite_note-33
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Miniseries_or_Television_Movie
/wiki/File:Black_Mass_PC_05_(21267276740).jpg
/wiki/Toronto_Film_Festival
/wiki/Matthew_Vaughn
/wiki/X-Men:_First_Class
/wiki/Sebastian_Shaw_(character)
#cite_note-34
#cite_note-35
/wiki/Crazy,_Stupid,_Love
/wiki/Dustin_Lance_Black
/wiki/8_(play)
/wiki/Perry_v._Brown
/wiki/Proposition_8
/wiki/Charles_J._Cooper
#cite_note-8_the_play-36
/wiki/Wilshire_Ebell_Theatre
/wiki/American_Foundation_for_Equal_Rights
#cite_note-8_play_video-37
#cite_note-38
/wiki/The_Following
#cite_note-39
/wiki/Saturn_Award_for_Best_Actor_on_Television
#cite_note-40
/wiki/Black_Mass_(film)
/wiki/Johnny_Depp
/wiki/Huffington_Post
/wiki/Tremors_(1990_film)
#cite_note-41
/wiki/Tremors_5:_Bloodline
/wiki/Patriots_Day_(film)
/wiki/Boston_Marathon_bombing
/wiki/The_Bacon_Brothers
/wiki/Michael_Bacon_(musician)
#cite_note-42
/wiki/Instagram
#cite_note-43
/wiki/Old_97%27s
/wiki/The_Guardians_of_the_Galaxy_Holiday_Special
#cite_note-44
/wiki/EE_(telecommunications)
#cite_note-45
#cite_note-46
#cite_note-47
/wiki/Six_Degrees_of_Kevin_Bacon
/wiki/File:Kevin_Bacon_2_SDCC_2014.jpg
/wiki/Trivia
/wiki/Big_screen
/wiki/Six_degrees_of_separation
/wiki/Internet_meme
/wiki/SixDegrees.org
/wiki/Social_networking_service
#cite_note-48
/wiki/Six_Degrees_of_Kevin_Bacon
/wiki/IMDb
#cite_note-49
/wiki/Paul_Erd%C5%91s
/wiki/Erd%C5%91s_number
/wiki/Paul_Erd%C5%91s
/wiki/Erd%C5%91s_number
/wiki/Erd%C5%91s%E2%80%93Bacon_number
#cite_note-50
/wiki/File:Kyra_Sedgwick_and_Kevin_Bacon_The_Best_You_Can-28_(cropped).jpg
/wiki/Kyra_Sedgwick
/wiki/PBS
/wiki/Lanford_Wilson
/wiki/Lemon_Sky
#cite_note-cosmo91-10
/wiki/Pyrates
/wiki/Murder_in_the_First_(film)
/wiki/The_Woodsman_(2004_film)
/wiki/Loverboy_(2005_film)
/wiki/Sosie_Bacon
/wiki/Upper_West_Side
/wiki/Manhattan
#cite_note-51
/wiki/Tracy_Pollan
#cite_note-52
/wiki/Separation_of_church_and_state_in_the_United_States
#cite_note-53
#cite_note-54
/wiki/The_Times
/wiki/Atheism
#cite_note-55
/wiki/Antireligion
#cite_note-56
/wiki/Will.i.am
/wiki/It%27s_a_New_Day_(Will.i.am_song)
/wiki/Barack_Obama
/wiki/Wikipedia:Citation_needed
/wiki/Ponzi_scheme
/wiki/Bernie_Madoff
#cite_note-financialpost-57
#cite_note-58
/wiki/Finding_Your_Roots
/wiki/Henry_Louis_Gates
#cite_note-59
#cite_note-60
#cite_note-61
#cite_note-62
/wiki/Apollo_13_(film)
#cite_note-63
/wiki/Mystic_River_(film)
/wiki/Blockbuster_Entertainment_Awards
/wiki/Blockbuster_Entertainment_Awards
#cite_note-64
/wiki/Hollow_Man
/wiki/Boston_Society_of_Film_Critics
/wiki/Boston_Society_of_Film_Critics_Award_for_Best_Cast
#cite_note-65
/wiki/Mystic_River_(film)
/wiki/Bravo_Otto
/wiki/Bravo_Otto
/wiki/Footloose_(1984_film)
/wiki/CableACE_Award
/wiki/CableACE_Award
/wiki/Losing_Chase
/wiki/Chlotrudis_Awards
/wiki/The_Woodsman_(2004_film)
/wiki/Critics%27_Choice_Movie_Awards
/wiki/Critics%27_Choice_Movie_Award_for_Best_Actor
/wiki/Murder_in_the_First_(film)
/wiki/Ghent_International_Film_Festival
/wiki/Ghent_International_Film_Festival
/wiki/The_Woodsman_(2004_film)
/wiki/Giffoni_Film_Festival
/wiki/Giffoni_Film_Festival
/wiki/Digging_to_China
/wiki/Mystic_River_(film)
/wiki/Golden_Globe_Award
/wiki/Golden_Globe_Award_for_Best_Supporting_Actor_%E2%80%93_Motion_Picture
/wiki/The_River_Wild
/wiki/Golden_Globe_Award_for_Best_Actor_%E2%80%93_Miniseries_or_Television_Film
/wiki/Taking_Chance
/wiki/Golden_Globe_Award_for_Best_Actor_%E2%80%93_Television_Series_Musical_or_Comedy
/wiki/I_Love_Dick_(TV_series)
/wiki/Independent_Spirit_Awards
/wiki/Independent_Spirit_Award_for_Best_Male_Lead
/wiki/The_Woodsman_(2004_film)
/wiki/Mystic_River_(film)
/wiki/MTV_Movie_%26_TV_Awards
/wiki/MTV_Movie_Award_for_Best_Villain
/wiki/Hollow_Man
/wiki/Taking_Chance
/wiki/The_Following
/wiki/E!_People%27s_Choice_Awards
/wiki/E!_People%27s_Choice_Awards
/wiki/The_Following
/wiki/E!_People%27s_Choice_Awards
/wiki/The_Following
/wiki/Primetime_Emmy_Award
/wiki/Primetime_Emmy_Award_for_Outstanding_Lead_Actor_in_a_Limited_Series_or_Movie
/wiki/Taking_Chance
/wiki/Satellite_Awards
/wiki/Satellite_Award_for_Best_Actor_%E2%80%93_Motion_Picture
/wiki/The_Woodsman_(2004_film)
/wiki/Satellite_Award_for_Best_Actor_%E2%80%93_Miniseries_or_Television_Film
/wiki/Taking_Chance
/wiki/Saturn_Award
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/The_Following
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/The_Following
/wiki/Scream_Awards
/wiki/Scream_Awards
/wiki/X-Men:_First_Class
/wiki/Screen_Actors_Guild_Award
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Supporting_Role
/wiki/Murder_in_the_First_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Cast_in_a_Motion_Picture
/wiki/Apollo_13_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Cast_in_a_Motion_Picture
/wiki/Mystic_River_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Cast_in_a_Motion_Picture
/wiki/Frost/Nixon_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Miniseries_or_Television_Movie
/wiki/Taking_Chance
/wiki/Teen_Choice_Awards
/wiki/Teen_Choice_Award_for_Choice_Movie_Villain
/wiki/Beauty_Shop
/wiki/Teen_Choice_Award_for_Choice_Movie_Villain
/wiki/X-Men:_First_Class
/wiki/TV_Guide_Award
/wiki/TV_Guide_Award
/wiki/The_Following
/wiki/File:Kevin_Bacon%27s_Star_Walk_of_Fame.jpg
/wiki/Hollywood_Walk_of_Fame
/wiki/Hollywood_Walk_of_Fame
#cite_note-66
/wiki/Denver_Film_Festival
#cite_note-67
/wiki/Phoenix_Film_Festival
#cite_note-68
/wiki/Santa_Barbara_International_Film_Festival
#cite_note-69
/wiki/Broadcast_Film_Critics_Association
#cite_note-70
/wiki/Seattle_International_Film_Festival
#cite_note-71
/wiki/List_of_atheists_in_film,_radio,_television_and_theater
/wiki/List_of_actors_with_Hollywood_Walk_of_Fame_motion_picture_stars
#cite_ref-1
https://web.archive.org/web/20090113222205/http://www.newenglandancestors.org/research/services/articles_gbr78.asp
http://www.newenglandancestors.org/research/services/articles_gbr78.asp
#cite_ref-actor_2-0
#cite_ref-actor_2-1
#cite_ref-actor_2-2
http://www.biography.com/people/kevin-bacon-9542173
#cite_ref-3
https://www.hollywoodreporter.com/tv/tv-news/showtime-cancels-city-on-a-hill-3-seasons-1235250089/
/wiki/The_Hollywood_Reporter
#cite_ref-4
http://www.walkoffame.com/kevin-bacon
/wiki/Hollywood_Walk_of_Fame
#cite_ref-5
https://www.marketingweek.com/ee-unveils-six-degrees-of-bacon-launch-ads/
/wiki/Marketing_Week
#cite_ref-bacon_6-0
#cite_ref-bacon_6-1
#cite_ref-bacon_6-2
#cite_ref-bacon_6-3
https://web.archive.org/web/20190403203113/https://www.biography.com/news/kevin-bacon-biography-facts
http://www.biography.com/news/kevin-bacon-biography-facts
#cite_ref-7
https://philadelphia.cbslocal.com/top-lists/stars-from-philly-to-hollywood/
#cite_ref-8
https://movies.yahoo.com/person/kevin-bacon/biography.html
#cite_ref-walk_9-0
https://web.archive.org/web/20141016202657/http://www.thebiographychannel.co.uk/biographies/kevin-bacon.html
http://www.thebiographychannel.co.uk/biographies/kevin-bacon.html
#cite_ref-cosmo91_10-0
#cite_ref-cosmo91_10-1
#cite_ref-11
http://www.nydailynews.com/entertainment/happy-halloween-superstars-start-horror-flick-gallery-1.98345
#cite_ref-bio_12-0
#cite_ref-bio_12-1
#cite_ref-bio_12-2
#cite_ref-bio_12-3
#cite_ref-bio_12-4
#cite_ref-bio_12-5
#cite_ref-bio_12-6
#cite_ref-bio_12-7
#cite_ref-bio_12-8
#cite_ref-bio_12-9
#cite_ref-bio_12-10
https://web.archive.org/web/20160530033240/http://www.pbs.org/weta/finding-your-roots/profiles/kevin-bacon%c2%a0/
https://www.pbs.org/wnet/finding-your-roots/profiles/kevin-bacon%C2%A0/
#cite_ref-kevin_13-0
https://www.tvguide.com/celebrities/kevin-bacon/bio/160550
#cite_ref-14
https://web.archive.org/web/20141021030336/http://news.moviefone.com/2012/03/02/diner-30th-anniversary/
http://news.moviefone.com/2012/03/02/diner-30th-anniversary/
#cite_ref-time84_15-0
https://web.archive.org/web/20080830035710/http://www.time.com/time/magazine/article/0,9171,950019,00.html
http://www.time.com/time/magazine/article/0,9171,950019,00.html
#cite_ref-16
http://www.huffingtonpost.com/2014/08/25/kevin-bacon-footloose_n_5710413.html
#cite_ref-17
https://web.archive.org/web/20090109152125/http://www.thebiographychannel.co.uk/biography_story/522%3A492/1/Kevin_Bacon.htm
http://www.thebiographychannel.co.uk/biography_story/522:492/1/Kevin_Bacon.htm
#cite_ref-18
https://www.mentalfloss.com/article/71594/14-moving-facts-about-planes-trains-and-automobiles
#cite_ref-19
https://www.nytimes.com/1994/09/25/movies/a-second-wind-is-blowing-for-kevin-bacon.html
/wiki/The_New_York_Times
#cite_ref-20
https://www.nytimes.com/movie/review?res=9C0CE2DE1631F93AA25752C0A966958260
/wiki/The_New_York_Times
#cite_ref-nyt94_21-0
https://query.nytimes.com/gst/fullpage.html?res=9C07E6D91F3BF936A1575AC0A962958260
/wiki/The_New_York_Times
#cite_ref-22
http://www.jfk-online.com/jfkbacon.html
#cite_ref-23
https://www.tcm.com/this-month/article/143158
#cite_ref-24
https://collider.com/kevin-bacon-commercials-footloose/
#cite_ref-25
http://www.rogerebert.com/reviews/sleepers-1996
#cite_ref-austin_26-0
http://www.austinchronicle.com/calendar/film/1997-02-07/283342/
/wiki/The_Austin_Chronicle
#cite_ref-27

## Retrieving Articles Only

In [3]:
import re

bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')
for link in bs.find('div', {'id': 'bodyContent'}).find_all(
        'a', href=re.compile('^(/wiki/)((?!:).)*$')):
    print(link.attrs['href'])

/wiki/Kevin_Bacon_(disambiguation)
/wiki/Philadelphia
/wiki/Kevin_Bacon_filmography
/wiki/Kyra_Sedgwick
/wiki/Sosie_Bacon
/wiki/Edmund_Bacon_(architect)
/wiki/Michael_Bacon_(composer)
/wiki/Leading_man
/wiki/Golden_Globe_Award
/wiki/Actor_Award
/wiki/National_Lampoon%27s_Animal_House
/wiki/Diner_(1982_film)
/wiki/Footloose_(1984_film)
/wiki/JFK_(film)
/wiki/A_Few_Good_Men
/wiki/Apollo_13_(film)
/wiki/Mystic_River_(film)
/wiki/Frost/Nixon_(film)
/wiki/Friday_the_13th_(1980_film)
/wiki/Tremors_(1990_film)
/wiki/The_River_Wild
/wiki/Balto_(film)
/wiki/The_Woodsman_(2004_film)
/wiki/Crazy,_Stupid,_Love
/wiki/Patriots_Day_(film)
/wiki/Losing_Chase
/wiki/Loverboy_(2005_film)
/wiki/Golden_Globe_Award_for_Best_Actor_%E2%80%93_Miniseries_or_Television_Film
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Miniseries_or_Television_Movie
/wiki/Michael_Strobl
/wiki/HBO
/wiki/Taking_Chance
/wiki/Fox_Broadcasting_Company
/wiki/The_Following
/wiki/Amazon_Prime_Video
/wiki/I_Love_Dick_(TV_series)
/wiki/Showtime_(TV_network)
/wiki/City_on_a_Hill_(TV_series)
/wiki/Hollywood_Walk_of_Fame
/wiki/Six_Degrees_of_Kevin_Bacon
/wiki/Brand_ambassador
/wiki/EE_(telecommunications)
/wiki/Kyra_Sedgwick
/wiki/Philadelphia
/wiki/Birth_name#Maiden_and_married_names
/wiki/Edmund_Bacon_(architect)
/wiki/Urban_planning
/wiki/Design_of_Cities
/wiki/Julia_R._Masterman_School
/wiki/Spring_Garden,_Philadelphia
/wiki/Pennsylvania_Governor%27s_School_for_the_Arts
/wiki/Bucknell_University
/wiki/Lewisburg,_Pennsylvania
/wiki/Glory_Van_Scott
/wiki/Kevin_Bacon_filmography
/wiki/Circle_in_the_Square
/wiki/Nancy_Mills
/wiki/Cosmopolitan_(magazine)
/wiki/Fraternities_and_sororities
/wiki/Animal_House
/wiki/Search_for_Tomorrow
/wiki/Guiding_Light
/wiki/Friday_the_13th_(1980_film)
/wiki/Getting_Out
/wiki/Phoenix_Theater
/wiki/Flux
/wiki/Second_Stage_Theatre
/wiki/Obie_Award
/wiki/Forty_Deuce
/wiki/Slab_Boys
/wiki/Sean_Penn
/wiki/Val_Kilmer
/wiki/Barry_Levinson
/wiki/Diner_(1982_film)
/wiki/Steve_Guttenberg
/wiki/Daniel_Stern_(actor)
/wiki/Mickey_Rourke
/wiki/Tim_Daly
/wiki/Ellen_Barkin
/wiki/Footloose_(1984_film)
/wiki/James_Dean
/wiki/Rebel_Without_a_Cause
/wiki/Mickey_Rooney
/wiki/Judy_Garland
/wiki/Typecasting_(acting)
/wiki/John_Hughes_(filmmaker)
/wiki/Planes,_Trains_and_Automobiles
/wiki/She%27s_Having_a_Baby
/wiki/The_Big_Picture_(1989_film)
/wiki/Tremors_(1990_film)
/wiki/Joel_Schumacher
/wiki/Flatliners
/wiki/Elizabeth_Perkins
/wiki/He_Said,_She_Said_(film)
/wiki/The_New_York_Times
/wiki/Oliver_Stone
/wiki/JFK_(film)
/wiki/A_Few_Good_Men_(film)
/wiki/Michael_Greif
/wiki/Golden_Globe_Award
/wiki/The_River_Wild
/wiki/Meryl_Streep
/wiki/Murder_in_the_First_(film)
/wiki/Blockbuster_(entertainment)
/wiki/Apollo_13_(film)
/wiki/Sleepers_(film)
/wiki/Picture_Perfect_(1997_film)
/wiki/Losing_Chase
/wiki/Digging_to_China
/wiki/Payola
/wiki/Telling_Lies_in_America_(film)
/wiki/Wild_Things_(film)
/wiki/Stir_of_Echoes
/wiki/David_Koepp
/wiki/Cannes_Film_Festival
/wiki/Paul_Verhoeven
/wiki/Hollow_Man
/wiki/Colin_Firth
/wiki/Rachel_Blanchard
/wiki/M%C3%A9nage_%C3%A0_trois
/wiki/Where_the_Truth_Lies
/wiki/Atom_Egoyan
/wiki/MPAA
/wiki/MPAA_film_rating_system
/wiki/My_Dog_Skip_(film)
/wiki/Sean_Penn
/wiki/Tim_Robbins
/wiki/Clint_Eastwood
/wiki/Mystic_River_(film)
/wiki/The_Woodsman_(2004_film)
/wiki/Beauty_Shop
/wiki/Queen_Latifah
/wiki/HBO_Films
/wiki/Taking_Chance
/wiki/Michael_Strobl
/wiki/Desert_Storm
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Miniseries_or_Television_Movie
/wiki/Toronto_Film_Festival
/wiki/Matthew_Vaughn
/wiki/Sebastian_Shaw_(character)
/wiki/Crazy,_Stupid,_Love
/wiki/Dustin_Lance_Black
/wiki/8_(play)
/wiki/Perry_v._Brown
/wiki/Proposition_8
/wiki/Charles_J._Cooper
/wiki/Wilshire_Ebell_Theatre
/wiki/American_Foundation_for_Equal_Rights
/wiki/The_Following
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/Black_Mass_(film)
/wiki/Johnny_Depp
/wiki/Huffington_Post
/wiki/Tremors_(1990_film)
/wiki/Patriots_Day_(film)
/wiki/Boston_Marathon_bombing
/wiki/The_Bacon_Brothers
/wiki/Michael_Bacon_(musician)
/wiki/Instagram
/wiki/Old_97%27s
/wiki/The_Guardians_of_the_Galaxy_Holiday_Special
/wiki/EE_(telecommunications)
/wiki/Six_Degrees_of_Kevin_Bacon
/wiki/Trivia
/wiki/Big_screen
/wiki/Six_degrees_of_separation
/wiki/Internet_meme
/wiki/SixDegrees.org
/wiki/Social_networking_service
/wiki/Six_Degrees_of_Kevin_Bacon
/wiki/IMDb
/wiki/Paul_Erd%C5%91s
/wiki/Erd%C5%91s_number
/wiki/Paul_Erd%C5%91s
/wiki/Erd%C5%91s_number
/wiki/Erd%C5%91s%E2%80%93Bacon_number
/wiki/Kyra_Sedgwick
/wiki/PBS
/wiki/Lanford_Wilson
/wiki/Lemon_Sky
/wiki/Pyrates
/wiki/Murder_in_the_First_(film)
/wiki/The_Woodsman_(2004_film)
/wiki/Loverboy_(2005_film)
/wiki/Sosie_Bacon
/wiki/Upper_West_Side
/wiki/Manhattan
/wiki/Tracy_Pollan
/wiki/Separation_of_church_and_state_in_the_United_States
/wiki/The_Times
/wiki/Atheism
/wiki/Antireligion
/wiki/Will.i.am
/wiki/It%27s_a_New_Day_(Will.i.am_song)
/wiki/Barack_Obama
/wiki/Ponzi_scheme
/wiki/Bernie_Madoff
/wiki/Finding_Your_Roots
/wiki/Henry_Louis_Gates
/wiki/Apollo_13_(film)
/wiki/Mystic_River_(film)
/wiki/Blockbuster_Entertainment_Awards
/wiki/Blockbuster_Entertainment_Awards
/wiki/Hollow_Man
/wiki/Boston_Society_of_Film_Critics
/wiki/Boston_Society_of_Film_Critics_Award_for_Best_Cast
/wiki/Mystic_River_(film)
/wiki/Bravo_Otto
/wiki/Bravo_Otto
/wiki/Footloose_(1984_film)
/wiki/CableACE_Award
/wiki/CableACE_Award
/wiki/Losing_Chase
/wiki/Chlotrudis_Awards
/wiki/The_Woodsman_(2004_film)
/wiki/Critics%27_Choice_Movie_Awards
/wiki/Critics%27_Choice_Movie_Award_for_Best_Actor
/wiki/Murder_in_the_First_(film)
/wiki/Ghent_International_Film_Festival
/wiki/Ghent_International_Film_Festival
/wiki/The_Woodsman_(2004_film)
/wiki/Giffoni_Film_Festival
/wiki/Giffoni_Film_Festival
/wiki/Digging_to_China
/wiki/Mystic_River_(film)
/wiki/Golden_Globe_Award
/wiki/Golden_Globe_Award_for_Best_Supporting_Actor_%E2%80%93_Motion_Picture
/wiki/The_River_Wild
/wiki/Golden_Globe_Award_for_Best_Actor_%E2%80%93_Miniseries_or_Television_Film
/wiki/Taking_Chance
/wiki/Golden_Globe_Award_for_Best_Actor_%E2%80%93_Television_Series_Musical_or_Comedy
/wiki/I_Love_Dick_(TV_series)
/wiki/Independent_Spirit_Awards
/wiki/Independent_Spirit_Award_for_Best_Male_Lead
/wiki/The_Woodsman_(2004_film)
/wiki/Mystic_River_(film)
/wiki/MTV_Movie_%26_TV_Awards
/wiki/MTV_Movie_Award_for_Best_Villain
/wiki/Hollow_Man
/wiki/Taking_Chance
/wiki/The_Following
/wiki/E!_People%27s_Choice_Awards
/wiki/E!_People%27s_Choice_Awards
/wiki/The_Following
/wiki/E!_People%27s_Choice_Awards
/wiki/The_Following
/wiki/Primetime_Emmy_Award
/wiki/Primetime_Emmy_Award_for_Outstanding_Lead_Actor_in_a_Limited_Series_or_Movie
/wiki/Taking_Chance
/wiki/Satellite_Awards
/wiki/Satellite_Award_for_Best_Actor_%E2%80%93_Motion_Picture
/wiki/The_Woodsman_(2004_film)
/wiki/Satellite_Award_for_Best_Actor_%E2%80%93_Miniseries_or_Television_Film
/wiki/Taking_Chance
/wiki/Saturn_Award
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/The_Following
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/The_Following
/wiki/Scream_Awards
/wiki/Scream_Awards
/wiki/Screen_Actors_Guild_Award
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Supporting_Role
/wiki/Murder_in_the_First_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Cast_in_a_Motion_Picture
/wiki/Apollo_13_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Cast_in_a_Motion_Picture
/wiki/Mystic_River_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Cast_in_a_Motion_Picture
/wiki/Frost/Nixon_(film)
/wiki/Screen_Actors_Guild_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Miniseries_or_Television_Movie
/wiki/Taking_Chance
/wiki/Teen_Choice_Awards
/wiki/Teen_Choice_Award_for_Choice_Movie_Villain
/wiki/Beauty_Shop
/wiki/Teen_Choice_Award_for_Choice_Movie_Villain
/wiki/TV_Guide_Award
/wiki/TV_Guide_Award
/wiki/The_Following
/wiki/Hollywood_Walk_of_Fame
/wiki/Hollywood_Walk_of_Fame
/wiki/Denver_Film_Festival
/wiki/Phoenix_Film_Festival
/wiki/Santa_Barbara_International_Film_Festival
/wiki/Broadcast_Film_Critics_Association
/wiki/Seattle_International_Film_Festival
/wiki/List_of_atheists_in_film,_radio,_television_and_theater
/wiki/List_of_actors_with_Hollywood_Walk_of_Fame_motion_picture_stars
/wiki/The_Hollywood_Reporter
/wiki/Hollywood_Walk_of_Fame
/wiki/Marketing_Week
/wiki/The_New_York_Times
/wiki/The_New_York_Times
/wiki/The_New_York_Times
/wiki/The_Austin_Chronicle
/wiki/The_New_York_Times
/wiki/Access_Hollywood
/wiki/CNN
/wiki/IMDb_(identifier)
/wiki/Internet_Broadway_Database
/wiki/Internet_Off-Broadway_Database
/wiki/Kevin_Bacon_filmography
/wiki/Losing_Chase
/wiki/Loverboy_(2005_film)
/wiki/Family_Movie
/wiki/Kyra_Sedgwick
/wiki/Sosie_Bacon
/wiki/Edmund_Bacon_(architect)
/wiki/Michael_Bacon_(composer)
/wiki/The_Bacon_Brothers
/wiki/Six_Degrees_of_Kevin_Bacon
/wiki/Erd%C5%91s%E2%80%93Bacon_number
/wiki/SixDegrees.org
/wiki/Actor_Award_for_Outstanding_Performance_by_a_Male_Actor_in_a_Miniseries_or_Television_Movie
/wiki/Raul_Julia
/wiki/Gary_Sinise
/wiki/Alan_Rickman
/wiki/Gary_Sinise
/wiki/Christopher_Reeve
/wiki/Jack_Lemmon
/wiki/Brian_Dennehy
/wiki/Ben_Kingsley
/wiki/William_H._Macy
/wiki/Al_Pacino
/wiki/Geoffrey_Rush
/wiki/Paul_Newman
/wiki/Jeremy_Irons
/wiki/Kevin_Kline
/wiki/Paul_Giamatti
/wiki/Al_Pacino
/wiki/Paul_Giamatti
/wiki/Kevin_Costner
/wiki/Michael_Douglas
/wiki/Mark_Ruffalo
/wiki/Idris_Elba
/wiki/Bryan_Cranston
/wiki/Alexander_Skarsg%C3%A5rd
/wiki/Darren_Criss
/wiki/Sam_Rockwell
/wiki/Mark_Ruffalo
/wiki/Michael_Keaton
/wiki/Sam_Elliott
/wiki/Steven_Yeun
/wiki/Colin_Farrell
/wiki/Owen_Cooper
/wiki/Santa_Barbara_International_Film_Festival#American_Riviera_Award
/wiki/Diane_Lane
/wiki/Philip_Seymour_Hoffman
/wiki/Forest_Whitaker
/wiki/Tommy_Lee_Jones
/wiki/Mickey_Rourke
/wiki/Sandra_Bullock
/wiki/Annette_Bening
/wiki/Martin_Scorsese
/wiki/Quentin_Tarantino
/wiki/Robert_Redford
/wiki/Patricia_Arquette
/wiki/Ethan_Hawke
/wiki/Michael_Keaton
/wiki/Rachel_McAdams
/wiki/Mark_Ruffalo
/wiki/Jeff_Bridges
/wiki/Sam_Rockwell
/wiki/Viggo_Mortensen
/wiki/Ren%C3%A9e_Zellweger
/wiki/Delroy_Lindo
/wiki/Kristen_Stewart
/wiki/Brendan_Fraser
/wiki/Mark_Ruffalo
/wiki/Zoe_Salda%C3%B1a
/wiki/Ethan_Hawke
/wiki/39th_Santa_Barbara_International_Film_Festival
/wiki/40th_Santa_Barbara_International_Film_Festival
/wiki/41st_Santa_Barbara_International_Film_Festival
/wiki/Critics%27_Choice_Movie_Award_for_Best_Actor
/wiki/Geoffrey_Rush
/wiki/Jack_Nicholson
/wiki/Ian_McKellen
/wiki/Russell_Crowe
/wiki/Russell_Crowe
/wiki/Russell_Crowe
/wiki/Daniel_Day-Lewis
/wiki/Jack_Nicholson
/wiki/Sean_Penn
/wiki/Jamie_Foxx
/wiki/Philip_Seymour_Hoffman
/wiki/Forest_Whitaker
/wiki/Daniel_Day-Lewis
/wiki/Sean_Penn
/wiki/Jeff_Bridges
/wiki/Colin_Firth
/wiki/George_Clooney
/wiki/Daniel_Day-Lewis
/wiki/Matthew_McConaughey
/wiki/Michael_Keaton
/wiki/Leonardo_DiCaprio
/wiki/Casey_Affleck
/wiki/Gary_Oldman
/wiki/Christian_Bale
/wiki/Joaquin_Phoenix
/wiki/Chadwick_Boseman
/wiki/Will_Smith
/wiki/Brendan_Fraser
/wiki/Paul_Giamatti
/wiki/Adrien_Brody
/wiki/Timoth%C3%A9e_Chalamet
/wiki/Golden_Globe_Award_for_Best_Actor_%E2%80%93_Miniseries_or_Television_Film
/wiki/Mickey_Rooney
/wiki/Anthony_Andrews
/wiki/Richard_Chamberlain
/wiki/Ted_Danson
/wiki/Dustin_Hoffman
/wiki/James_Woods
/wiki/Randy_Quaid
/wiki/Michael_Caine
/wiki/Stacy_Keach
/wiki/Robert_Duvall
/wiki/James_Garner
/wiki/Beau_Bridges
/wiki/Robert_Duvall
/wiki/James_Garner
/wiki/Raul_Julia
/wiki/Gary_Sinise
/wiki/Alan_Rickman
/wiki/Ving_Rhames
/wiki/Stanley_Tucci
/wiki/Jack_Lemmon
/wiki/Brian_Dennehy
/wiki/James_Franco
/wiki/Albert_Finney
/wiki/Al_Pacino
/wiki/Geoffrey_Rush
/wiki/Jonathan_Rhys_Meyers
/wiki/Bill_Nighy
/wiki/Jim_Broadbent
/wiki/Paul_Giamatti
/wiki/Al_Pacino
/wiki/Idris_Elba
/wiki/Kevin_Costner
/wiki/Michael_Douglas
/wiki/Billy_Bob_Thornton
/wiki/Oscar_Isaac
/wiki/Tom_Hiddleston
/wiki/Ewan_McGregor
/wiki/Darren_Criss
/wiki/Russell_Crowe
/wiki/Mark_Ruffalo
/wiki/Michael_Keaton
/wiki/Evan_Peters
/wiki/Steven_Yeun
/wiki/Colin_Farrell
/wiki/Stephen_Graham
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/Kyle_Chandler
/wiki/Steven_Weber
/wiki/Richard_Dean_Anderson
/wiki/David_Boreanaz
/wiki/Robert_Patrick
/wiki/Ben_Browder
/wiki/David_Boreanaz
/wiki/David_Boreanaz
/wiki/Ben_Browder
/wiki/Matthew_Fox
/wiki/Michael_C._Hall
/wiki/Matthew_Fox
/wiki/Edward_James_Olmos
/wiki/Josh_Holloway
/wiki/Stephen_Moyer
/wiki/Bryan_Cranston
/wiki/Bryan_Cranston
/wiki/Mads_Mikkelsen
/wiki/Hugh_Dancy
/wiki/Andrew_Lincoln
/wiki/Bruce_Campbell
/wiki/Andrew_Lincoln
/wiki/Kyle_MacLachlan
/wiki/Patrick_Stewart
/wiki/Saturn_Award_for_Best_Actor_in_a_Network_or_Cable_Television_Series
/wiki/Sam_Heughan
/wiki/Bob_Odenkirk
/wiki/Saturn_Award_for_Best_Actor_in_a_Streaming_Television_Series
/wiki/Henry_Thomas
/wiki/Oscar_Isaac
/wiki/Saturn_Award_for_Best_Actor_on_Television
/wiki/Patrick_Stewart
/wiki/Colin_Farrell
/wiki/Diego_Luna

## Random Walk

In [4]:
import datetime, random, re

random.seed(datetime.datetime.now().timestamp())

def getLinks(articleUrl):
    bs = get_soup(f'https://en.wikipedia.org{articleUrl}')
    return bs.find('div', {'id': 'bodyContent'}).find_all(
        'a', href=re.compile('^(/wiki/)((?!:).)*$'))

MAX_HOPS = 8
links = getLinks('/wiki/Kevin_Bacon')
hops = 0
while len(links) > 0 and hops < MAX_HOPS:
    newArticle = links[random.randint(0, len(links)-1)].attrs['href']
    print(newArticle)
    links = getLinks(newArticle)
    hops += 1
print(f'\nStopped after {hops} hops.')

/wiki/Erd%C5%91s%E2%80%93Bacon_number
/wiki/Twilight_(2008_film)
/wiki/Young_Artist_Awards
/wiki/35th_Young_Artist_Awards
/wiki/Spooksville_(TV_series)
/wiki/35th_Young_Artist_Awards#Outstanding_Young_Ensemble_in_a_TV_Series
/wiki/4th_Youth_in_Film_Awards
/wiki/Archie_Bunker%27s_Place

Stopped after 8 hops.

## Recursively crawling an entire site

In [5]:
import re

pages = set()
MAX_PAGES = 25

def getLinks(pageUrl):
    if len(pages) >= MAX_PAGES:
        return
    bs = get_soup(f'https://en.wikipedia.org{pageUrl}')
    for link in bs.find_all('a', href=re.compile('^(/wiki/)')):
        if 'href' in link.attrs and link.attrs['href'] not in pages:
            if len(pages) >= MAX_PAGES:
                return
            newPage = link.attrs['href']
            print(newPage)
            pages.add(newPage)
            getLinks(newPage)

getLinks('/wiki/Kevin_Bacon')
print(f'\nCollected {len(pages)} pages (limit {MAX_PAGES}).')

/wiki/Main_Page
/wiki/Wikipedia:Contents
/wiki/Portal:Current_events
/wiki/Special:Random
/wiki/Wikipedia:About
/wiki/Help:Contents
/wiki/Help:Introduction
/wiki/Wikipedia:Community_portal
/wiki/Special:RecentChanges
/wiki/Special:Nearby
/wiki/Wikipedia:File_upload_wizard
/wiki/Special:SpecialPages
/wiki/Special:Search
/wiki/Help:Searching
/wiki/Help_talk:Searching
/wiki/Special:WhatLinksHere/Help_talk:Searching
/wiki/Help:What_links_here
/wiki/Help_talk:What_links_here
/wiki/Special:WhatLinksHere/Help_talk:What_links_here
/wiki/Help:What_links_here#Transclusion
/wiki/Special:WhatLinksHere/Help:What_links_here
/wiki/Template_talk:In_use
/wiki/Template:In_use
/wiki/Special:WhatLinksHere/Template:In_use
/wiki/Lithium

Collected 25 pages (limit 25).

## Collecting Data Across an Entire Site

In [6]:
import re

pages = set()
MAX_PAGES = 6

def getLinks(pageUrl):
    if len(pages) >= MAX_PAGES:
        return
    bs = get_soup(f'https://en.wikipedia.org{pageUrl}')
    try:
        print(bs.h1.get_text())
        bodyContent = bs.find('div', {'id': 'bodyContent'}).find_all('p')
        if len(bodyContent):
            print(bodyContent[0].get_text().strip()[:300])
    except AttributeError:
        print('This page is missing something! Continuing.')

    for link in bs.find_all('a', href=re.compile('^(/wiki/)((?!:).)*$')):
        if 'href' in link.attrs and link.attrs['href'] not in pages:
            if len(pages) >= MAX_PAGES:
                return
            newPage = link.attrs['href']
            print('-' * 20)
            print(newPage)
            pages.add(newPage)
            getLinks(newPage)

getLinks('/wiki/General-purpose_programming_language')

General-purpose programming language
In computer software, a general-purpose programming language (GPL) is a programming language for building software in a wide variety of application domains. Conversely, a domain-specific programming language (DSL) is used within a specific area. For example, Python is a GPL, while SQL is a DSL for q
--------------------
/wiki/Main_Page
Main Page
Vatican City's participation at the 2022 Mediterranean Games, held in Oran, Algeria, from 25 June to 6 July 2022, was as guests. It was the Vatican's first appearance in the Mediterranean Games, and its debut in any international multi-sport event. The Vatican's participation was the result of an ag
--------------------
/wiki/Wikipedia
Wikipedia

--------------------
/wiki/English_Wikipedia
English Wikipedia

--------------------
/wiki/Simple_English_Wikipedia
Simple English Wikipedia

--------------------
/wiki/Northern_S%C3%A1mi_Wikipedia
Northern Sámi Wikipedia

--------------------
/wiki/Internet_encyclopedia_project

## Collect all External Links from a Site

In [7]:
from urllib.parse import urlparse
import re

def getInternalLinks(bs, url):
    netloc = urlparse(url).netloc
    scheme = urlparse(url).scheme
    internalLinks = set()
    for link in bs.find_all('a'):
        if not link.attrs.get('href'):
            continue
        parsed = urlparse(link.attrs['href'])
        if parsed.netloc == '':
            internalLinks.add(f'{scheme}://{netloc}/{link.attrs["href"].strip("/")}')
        elif parsed.netloc == netloc:
            internalLinks.add(link.attrs['href'])
    return list(internalLinks)

def getExternalLinks(bs, url):
    netloc = urlparse(url).netloc
    externalLinks = set()
    for link in bs.find_all('a'):
        if not link.attrs.get('href'):
            continue
        parsed = urlparse(link.attrs['href'])
        if parsed.netloc != '' and parsed.netloc != netloc:
            externalLinks.add(link.attrs['href'])
    return list(externalLinks)

url = 'https://en.wikipedia.org/wiki/Kevin_Bacon'
bs = get_soup(url)
internal = getInternalLinks(bs, url)
external = getExternalLinks(bs, url)
print('Internal links:', len(internal))
print('External links:', len(external))
print('\nSample external:')
for l in external[:10]:
    print(' ', l)

Internal links: 601
External links: 196

Sample external:
  https://de.wikipedia.org/wiki/Kevin_Bacon
  https://cs.wikipedia.org/wiki/Kevin_Bacon
  https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en
  https://simple.wikipedia.org/wiki/Kevin_Bacon
  http://www.rogerebert.com/reviews/sleepers-1996
  https://web.archive.org/web/20100722010545/http://heatvision.hollywoodreporter.com/2010/07/winters-bone-star-cast-as-mystique-in-xmen-first-class.html
  https://web.archive.org/web/20080830035710/http://www.time.com/time/magazine/article/0,9171,950019,00.html
  https://azb.wikipedia.org/wiki/%DA%A9%D9%88%DB%8C%D9%86_%D8%A8%DB%8C%DA%A9%D9%86
  http://www.drawtheline.org/watch-stuff
  https://zh-min-nan.wikipedia.org/wiki/Kevin_Bacon

## Crawling across the Internet

In [8]:
import random

def getRandomExternalLink(startingPage):
    bs = get_soup(startingPage)
    externalLinks = getExternalLinks(bs, startingPage)
    if not externalLinks:
        internalLinks = getInternalLinks(bs, startingPage)
        if not internalLinks:
            return None
        return getRandomExternalLink(random.choice(internalLinks))
    return random.choice(externalLinks)

def followExternalOnly(startingSite, max_hops=5):
    site = startingSite
    for i in range(max_hops):
        try:
            site = getRandomExternalLink(site)
        except Exception as e:
            print(f'Stopped at hop {i}: {e}')
            return
        if not site:
            print('No external link found, stopping.')
            return
        print(f'Hop {i+1}: {site}')

followExternalOnly('https://www.oreilly.com/')

Hop 1: https://learning.oreilly.com/search/?query=author%3A%22Arianne%20Dee%22&extended_publisher_data=true&highlight=true&include_assessments=false&include_case_studies=true&include_courses=true&include_playlists=true&include_collections=true&include_notebooks=true&include_sandboxes=true&include_scenarios=true&is_academic_institution_account=false&source=suggestion&sort=date_added&facet_json=true&json_facets=true&page=0&include_facets=false
Stopped at hop 1: HTTP Error 403: Forbidden

---
# Experiments: different HTML tags and CSS attributes

### 1. Section headings — selecting by tag name
The `<h2>` tags are the section titles. Grabbing them gives a quick outline of the page without reading any of it.

In [9]:
bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')
headings = [h.get_text(strip=True) for h in bs.find_all(['h2', 'h3'])]
print(len(headings), 'headings found')
for h in headings:
    print(' -', h)

17 headings found
 - Contents
 - Early life and education
 - Acting career
 - Early work
 - 1980s
 - 1990s
 - 2000s
 - 2010s
 - Other ventures
 - Six Degrees of Kevin Bacon
 - Personal life
 - Accolades
 - Awards and nominations
 - Other honors
 - See also
 - References
 - External links

### 2. The infobox — selecting by CSS class
The box on the right of a Wikipedia article is a `<table class="infobox">`. Reading its `<th>`/`<td>` rows turns it into clean key/value facts, which is the kind of structured data worth scraping.

In [10]:
import pandas as pd

bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')
infobox = bs.find('table', class_='infobox')

facts = {}
for row in infobox.find_all('tr'):
    th, td = row.find('th'), row.find('td')
    if th and td:
        facts[th.get_text(' ', strip=True)] = td.get_text(' ', strip=True)

df = pd.DataFrame(list(facts.items()), columns=['Field', 'Value'])
df

          Field                                              Value
0          Born  Kevin Norwood Bacon ( 1958-07-08 ) July 8, 195...
1   Occupations                                     Actor musician
2  Years active                                       1977–present
3         Works                                        Filmography
4        Spouse                       Kyra Sedgwick ​ ( m. 1988) ​
5      Children                           2, including Sosie Bacon
6        Father                                       Edmund Bacon
7     Relatives                            Michael Bacon (brother)
8       Website                                     baconbros .com

### 3. CSS selectors with select()
`select()` takes the same selectors you'd write in CSS, which is often shorter than chaining `find`/`find_all`. `#id`, `.class`, `tag.class`, and attribute filters like `a[href^="/wiki/"]` all work.

In [11]:
bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')

print('infobox rows          :', len(bs.select('table.infobox tr')))
print('body paragraphs       :', len(bs.select('div#bodyContent p')))
print('internal wiki links   :', len(bs.select('div#bodyContent a[href^="/wiki/"]')))
print('external (https) links:', len(bs.select('div#bodyContent a[href^="https"]')))
# same article-only filter as before, but as one CSS line:
print('first 5 article links :')
for a in bs.select('div#bodyContent a[href^="/wiki/"]')[:5]:
    print('   ', a.get('href'))

infobox rows          : 11
body paragraphs       : 36
internal wiki links   : 560
external (https) links: 77
first 5 article links :
    /wiki/Wikipedia:Protection_policy#semi
    /wiki/Kevin_Bacon_(disambiguation)
    /wiki/File:Kevin_Bacon_The_Best_You_Can-55_(cropped).jpg
    /wiki/Philadelphia
    /wiki/Kevin_Bacon_filmography

### 4. What is the page actually made of:  counting tags
Counting every tag name shows where the content lives. On an article most of the weight is in `<a>`, `<li>` and `<span>`, which is why naive link scraping returns so much noise.

In [12]:
from collections import Counter

bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')
counts = Counter(tag.name for tag in bs.find_all(True))
for name, n in counts.most_common(12):
    print(f'{name:8} {n}')

a        1010
span     904
li       472
div      244
td       194
i        186
sup      109
link     107
b        90
tr       75
ul       70
cite     68

### 5. Citations — selecting by class to get sources
References sit in `<cite class="citation ...">` tags. Pulling them is a fast way to harvest a page's source list.

In [13]:
bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')
cites = bs.select('cite.citation')
print(len(cites), 'citations on the page. First 10:')
for c in cites[:10]:
    print(' -', c.get_text(' ', strip=True)[:120])

68 citations on the page. First 10:
 - Roberts, Gary Boyd. "Ten Further Hollywood Figures (or Groups Thereof)" . New England Historic Genealogical Society. Arc
 - "Kevin Bacon" . Biography.com . Retrieved July 21, 2012 .
 - Porter, Rick (October 27, 2022). " 'City on a Hill' Canceled After Three Seasons on Showtime" . The Hollywood Reporter .
 - "Hollywood Walk of Fame - Kevin Bacon" . Hollywood Walk of Fame . September 30, 2003 . Retrieved May 9, 2017 .
 - O'Reilly, Laura (October 1, 2012). "EE unveils 'six degrees of Bacon' launch ads" . Marketing Week . Retrieved January 4
 - "Kevin Bacon: 6 Things You Didn't Know" . biography.com. Archived from the original on April 3, 2019 . Retrieved October
 - "4 Stars From Philly To Hollywood" . CBS Philadelphia . CBS News. October 10, 2010 . Retrieved June 9, 2019 .
 - "ABOUT KEVIN BACON" . yahoo movies . Retrieved July 21, 2012 .
 - "Kevin Bacon biography" . biography channel. Archived from the original on October 16, 2014 . Retrieved October 12, 2014
 - "Happy Halloween: Stars who got their start in horror flicks" . nydailynews.com . Retrieved October 12, 2014 .

### 6. The filmography table straight into pandas
For a real `<table>`, `pandas.read_html` does the parsing for you and hands back a DataFrame. Faster than walking rows by hand when the table is well formed.

In [16]:
import pandas as pd
from io import StringIO

bs = get_soup('https://en.wikipedia.org/wiki/Kevin_Bacon')
tables = pd.read_html(StringIO(str(bs)))
print(len(tables), 'tables parsed from the page.')
# show the first reasonably sized table
for t in tables:
    if t.shape[0] >= 3 and t.shape[1] >= 2:
        display(t.head(10))
        break

11 tables parsed from the page.

     Kevin Bacon                                      Kevin Bacon.1
0  Bacon in 2025                                      Bacon in 2025
1           Born  Kevin Norwood Bacon July 8, 1958 (age 67) Phil...
2    Occupations                                     Actor musician
3   Years active                                       1977–present
4          Works                                        Filmography
5         Spouse                          Kyra Sedgwick ​(m. 1988)​
6       Children                           2, including Sosie Bacon
7         Father                                       Edmund Bacon
8      Relatives                            Michael Bacon (brother)
9        Website                                      baconbros.com